### ISSUE TITLE
Como você faz pra encontrar os servidores dos canais

### ISSUE THREAD

**Issue by vbjunior** [Ramys/Iptv-Brasil-2020#2]
Como encontrar os sites que compartilham o link m3u? Eu vi que muito da lista de vcs é o live-orig-oiplay.online, eu não sei como que faz pra achar esses servidores, queria ajuda.

**Comment by Ramys** [comment]
Use os links do David/The Guardian..
https://github.com/ElyDavidBR/THE-GUARDIAN
Ele atualiza todas as listas , e vc poderá usá-las sem precisar atualizar.
Obs: Salve o link dele em seus favoritos..(Não siga e n passe a lista dele, ele poderá bloquear seu IP..)e não marque como estrela..

**Comment by vbjunior** [comment]
Obrigado

**Comment by Marco4raujo** [comment]
Sou novo aqui e no quesito link dos canais.
Poderia me ajudar a entender qual o link posso pegar dele, para assistir os canais? um que tenha m3u seria isso?

**Comment by Ramys** [comment]
Tópico antigo e fechado.
Há um modo novo de pesca.
